import type { Product } from "./types";

export const mockProducts: Product[] = [
  // ── Pokémon TCG ────────────────────────────────
  {
    id: "pkmn-charizard-ex",
    name: "Charizard ex",
    game: "pokemon",
    category: "card",
    price: 189.90,
    originalPrice: 229.90,
    image: "/cards/pokecard.png",
    rarity: "ultra-rare",
    condition: "near-mint",
    set: "Obsidian Flames",
    language: "Português",
    description: "Charizard ex 223/197 - Arte especial da expansão Obsidian Flames. Carta em estado Near Mint, perfeita para colecionadores.",
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "pkmn-pikachu-vmax",
    name: "Pikachu VMAX",
    game: "pokemon",
    category: "card",
    price: 79.90,
    image: "/cards/pokecard.png",
    rarity: "ultra-rare",
    condition: "mint",
    set: "Vivid Voltage",
    language: "Inglês",
    description: "Pikachu VMAX 044/185 da coleção Vivid Voltage. Rainbow Rare em condição Mint.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "pkmn-mewtwo-gx",
    name: "Mewtwo & Mew GX",
    game: "pokemon",
    category: "card",
    price: 149.90,
    image: "/cards/pokecard.png",
    rarity: "secret-rare",
    condition: "near-mint",
    set: "Unified Minds",
    language: "Japonês",
    description: "Mewtwo & Mew GX 242/236 Arte Alternativa da coleção Unified Minds. Versão japonesa.",
    inStock: true,
    isNew: false,
  },
  {
    id: "pkmn-umbreon-vmax",
    name: "Umbreon VMAX",
    game: "pokemon",
    category: "card",
    price: 399.90,
    image: "/cards/pokecard.png",
    rarity: "secret-rare",
    condition: "mint",
    set: "Evolving Skies",
    language: "Inglês",
    description: "Umbreon VMAX 215/203 Alt Art. Uma das cartas mais valorizadas do Pokémon TCG moderno.",
    inStock: true,
    isFeatured: true,
  },

  // ── Magic: The Gathering ───────────────────────
  {
    id: "mtg-sheoldred",
    name: "Sheoldred, the Apocalypse",
    game: "magic",
    category: "card",
    price: 299.90,
    image: "/cards/magic.png",
    rarity: "mythic",
    condition: "near-mint",
    set: "Dominaria United",
    language: "Inglês",
    description: "Sheoldred, the Apocalypse - Mítica de Dominaria United. Uma das criaturas mais jogadas do formato Standard e Pioneer.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "mtg-ragavan",
    name: "Ragavan, Nimble Pilferer",
    game: "magic",
    category: "card",
    price: 249.90,
    image: "/cards/magic.png",
    rarity: "mythic",
    condition: "near-mint",
    set: "Modern Horizons 2",
    language: "Inglês",
    description: "Ragavan, Nimble Pilferer - Uma das criaturas mais poderosas do formato Modern.",
    inStock: true,
  },
  {
    id: "mtg-lotus-field",
    name: "Lotus Field",
    game: "magic",
    category: "card",
    price: 39.90,
    image: "/cards/magic.png",
    rarity: "rare",
    condition: "mint",
    set: "Core Set 2020",
    language: "Português",
    description: "Lotus Field do Core Set 2020. Terreno essencial para combos em Pioneer.",
    inStock: true,
  },

  // ── Yu-Gi-Oh! ──────────────────────────────────
  {
    id: "ygo-blue-eyes",
    name: "Dragão Branco de Olhos Azuis",
    game: "yugioh",
    category: "card",
    price: 159.90,
    originalPrice: 199.90,
    image: "/cards/yugioh.png",
    rarity: "ultra-rare",
    condition: "near-mint",
    set: "Legend of Blue Eyes",
    language: "Português",
    description: "Blue-Eyes White Dragon edição LOB. Um clássico icônico do Yu-Gi-Oh! em ótimo estado.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "ygo-dark-magician",
    name: "Mago Negro",
    game: "yugioh",
    category: "card",
    price: 89.90,
    image: "/cards/yugioh.png",
    rarity: "ultra-rare",
    condition: "lightly-played",
    set: "Starter Deck Yugi",
    language: "Português",
    description: "Dark Magician do Starter Deck Yugi. Uma peça de colecionador.",
    inStock: true,
  },
  {
    id: "ygo-ash-blossom",
    name: "Ash Blossom & Joyous Spring",
    game: "yugioh",
    category: "card",
    price: 69.90,
    image: "/cards/yugioh.png",
    rarity: "secret-rare",
    condition: "mint",
    set: "Maximum Crisis",
    language: "Inglês",
    description: "Ash Blossom & Joyous Spring - Hand trap essencial para qualquer deck competitivo.",
    inStock: true,
  },

  // ── Acessórios ──────────────────────────────────
  {
    id: "acc-sleeves-pokeball",
    name: "Sleeves Pokéball Premium (65un)",
    game: "pokemon",
    category: "accessory",
    price: 34.90,
    image: "",
    description: "Protetores de carta com estampa de Pokéball. 65 unidades, qualidade japonesa.",
    inStock: true,
    isNew: true,
  },
  {
    id: "acc-deck-box-mtg",
    name: "Deck Box Ultra PRO - Mana Colors",
    game: "magic",
    category: "accessory",
    price: 49.90,
    image: "",
    description: "Deck Box oficial Ultra PRO com arte dos 5 tipos de mana de Magic. Comporta até 100 cartas com sleeve.",
    inStock: true,
  },
  {
    id: "acc-binder-9pocket",
    name: "Fichário 9 Bolsos - Premium Black",
    game: "pokemon",
    category: "accessory",
    price: 89.90,
    originalPrice: 109.90,
    image: "",
    description: "Fichário premium com 9 bolsos por página. 360 slots para cartas. Capa de couro sintético preto.",
    inStock: true,
    isFeatured: true,
  },
  {
    id: "acc-playmat-yugioh",
    name: "Playmat Oficial Konami - Blue-Eyes",
    game: "yugioh",
    category: "accessory",
    price: 129.90,
    image: "",
    description: "Playmat oficial Konami com arte do Blue-Eyes White Dragon. Material emborrachado premium.",
    inStock: true,
  },
];
